### ISSUE TITLE
Insertion Sort í glósunum virkar ekki

### ISSUE THREAD

**Issue by Sveppi** [ofurtumi/greining-reiknirita#2]
Röðunin virkar ekki, þarf að vera svona:

def insertionSort(A):
    i = 1
    while i < len(A):
      j = i
      while j > 0 and A[j-1] > A[j]:
          A[j], A[j-1] = A[j-1], A[j]
          j = j - 1
      i = i + 1
    return A

**Comment by ofurtumi** [comment]
vel spottað, laga núna

**Comment by Sveppi** [comment]
😘
